const { Router } = require('../utils/router')
const myController = require('../controllers/controllerIndex')

var router = new Router()

router.post('https://webclassmanager.herokuapp.com/api/register', myController.register)
router.post('https://webclassmanager.herokuapp.com/api/auth', myController.authenticate)
router.get('https://webclassmanager.herokuapp.com/api/user', myController.identifyUser)
router.get('https://webclassmanager.herokuapp.com/api/homepage', myController.homepage)
router.get('https://webclassmanager.herokuapp.com/api/course', myController.courseInfo)
router.put('https://webclassmanager.herokuapp.com/api/update', myController.settingsAccount)
router.get('https://webclassmanager.herokuapp.com/api/logout', myController.logout)
router.post('https://webclassmanager.herokuapp.com/api/enter-new-class', myController.enterNewClass)
router.get('https://webclassmanager.herokuapp.com/api/grades', myController.getStudentGrades)
router.get('https://webclassmanager.herokuapp.com/api/assignments', myController.getClassAssignments)
router.post('https://webclassmanager.herokuapp.com/api/create-class', myController.createNewClass)
router.get('https://webclassmanager.herokuapp.com/api/assignment', myController.getAssignment)
router.get('https://webclassmanager.herokuapp.com/api/all-assignments', myController.getAllStudentAssignment)
router.get('https://webclassmanager.herokuapp.com/api/catalog', myController.getClassCatalog)
router.get('https://webclassmanager.herokuapp.com/api/news', myController.getNews)
router.post('https://webclassmanager.herokuapp.com/api/present', myController.validatePresence)
router.get(`https://webclassmanager.herokuapp.com/api/download`, myController.downloadFile)
router.post(`https://webclassmanager.herokuapp.com/api/upload`, myController.newUpload)
router.put('https://webclassmanager.herokuapp.com/api/start', myController.start)
router.put('https://webclassmanager.herokuapp.com/api/catalog/save', myController.saveCatalog)
router.post('https://webclassmanager.herokuapp.com/api/catalog/calculateFinalGrade', myController.calculateFinalGrade)
router.get('https://webclassmanager.herokuapp.com/api/requests', myController.getRequests)
router.delete('https://webclassmanager.herokuapp.com/api/request', myController.processRequest)
router.get('https://webclassmanager.herokuapp.com/api/course/load', myController.loadCourseInfo)
router.post('https://webclassmanager.herokuapp.com/api/update/class', myController.updateClass)
router.get('https://webclassmanager.herokuapp.com/api/assignment/assignments', myController.getAssignmentsFromAssignment)

module.exports.index = router
